// Fallback copy of images/sprites/sprite-map.json for file:// use. Regenerate with tools/build_cards.py
var KV_SPRITE_MAP = {
 "Catapult": "r6c0",
 "Grim Reaper": "r3c7",
 "Stealth Warrior": "r1c2",
 "Frost Giant": "r5c1",
 "Titan": "r5c11",
 "Chariot Warrior": "r6c5",
 "Iron Giant": "r7c11",
 "Berserker Warrior": "r1c5",
 "Lightning Ninja": "r1c11",
 "Samurai": "r1c9",
 "Hammer Dwarf": "r1c4",
 "Blood Hound": "r4c2",
 "Captain": "r0c4",
 "Elf Rampager": "r1c1",
 "Tactical Warrior": "r0c1",
 "Attack Wagon": "r6c8",
 "Ranger": "r1c0",
 "Fire Sentinel": "r5c2",
 "Eagle Warrior": "r7c4",
 "Centurion": "r3c0",
 "Cannon": "r6c2",
 "Avenger": "r0c5",
 "Cobalt Knight": "r4c6",
 "Bomb Expert": "r0c10",
 "Venom Warrior": "r5c9",
 "Elephant Mounted Warrior": "r6c6",
 "Heavily Armored Soldier": "r3c2",
 "Stationary Crossbow Soldier": "r6c1",
 "Joker": "r2c3",
 "Morphing Warrior": "r3c11",
 "Militia": "r0c12",
 "Front Lineman": "r1c7",
 "Horse Mounted Troop": "r3c1",
 "Foot Soldier": "r4c1",
 "Archer": "r1c3",
 "Knight": "r0c3",
 "Minotaur": "r5c12",
 "Wizard": "r0c6",
 "Ent": "r5c3",
 "Brute": "r3c12",
 "General": "r0c2",
 "Commander": "r2c6",
 "Reviver": "r0c11",
 "Unskilled Warrior": "r2c4",
 "Phoenix": "r7c8",
 "Dwarf Blitzer": "r1c6",
 "Lightning Wizard": "r5c7",
 "Thunder Warrior": "r3c9",
 "Elf Blitz Warrior": "r7c1",
 "Peasant Mob": "r2c5",
 "Apprentice": "r6c11",
 "The Manipulator": "r4c3",
 "Blade Dancer": "r0c8",
 "Dragon Ninja": "r4c11",
 "Dragon Tamer": "r4c10",
 "Lightning Mage": "r5c4",
 "Field Marshall": "r6c3",
 "Spy": "r2c8",
 "Major": "r7c6",
 "Admiral": "r6c12",
 "Chemical Warfare Warrior": "r5c8",
 "Redstone Warrior": "r3c10",
 "Fire Striker": "r7c3",
 "Shadow Warrior": "r5c6",
 "Royal Assassin": "r1c12",
 "Magma Knight": "r4c9",
 "Frost Brute": "r4c0",
 "Tactical Ninja": "r0c9",
 "Armored Warrior": "r3c3",
 "The Supplier": "r6c4",
 "Bounty Hunter": "r2c2",
 "Juggernaut": "r3c8",
 "Hydra": "r7c9",
 "Ranged Expert": "r1c10",
 "Melee Expert": "r2c1",
 "Ace": "r2c10",
 "Kings Knight": "r4c7",
 "Rookie": "r0c0",
 "Unstable Bomb Expert": "r2c11",
 "Stone Monster": "r7c10",
 "Tactical Alchemist": "r2c7",
 "General's Guard": "r3c6",
 "Generals Bodyguard": "r2c12",
 "Guardian": "r6c7",
 "Ice Sentinel": "r4c12",
 "Lava Guardian": "r4c8",
 "Fallen Knight": "r3c5",
 "Dark Knight": "r3c4",
 "Strategic Warrior": "r2c9",
 "Medic": "r2c0",
 "War Captain": "r6c10",
 "Corrupt Commander": "r5c10",
 "Unstable Titan": "r4c4",
 "Hog Mounted Brute": "r7c5",
 "Stone Golem": "r5c0",
 "Elite Assasin": "r0c7",
 "Spartan": "r1c8",
 "Light Dragon": "r7c7",
 "Wolf Mounted Dwarf": "r4c5",
 "Fire Sprite": "r7c0",
 "Wisp": "r5c5",
 "Neon Wisp": "r7c2",
 "Wisp Captain": "r7c12",
 "Wisp Major": "r6c9"
};
